# ---- build stage ----
FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# build static binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o iCalToJson .


# ---- runtime stage ----
FROM alpine:3.20

# REQUIRED for Europe/London, etc.
RUN apk add --no-cache tzdata ca-certificates

WORKDIR /

COPY --from=builder /app/iCalToJson /iCalToJson

EXPOSE 8080

ENTRYPOINT ["/iCalToJson"]